version: "3.9"
services:
  product:
    build: ./product
    container_name: ecomm-product
    ports:
      - 3001:3001
    volumes:
      - ./product:/app-product
  account:
    build: ./account
    container_name: ecomm-account
    ports:
      - 3002:3002
    volumes:
      - ./account:/app-account
  mongodb:
    image: mongo:5
    container_name: mongo-ecomm
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: secret
    volumes:
      - mongodb-ecomm:/var/lib/mongodb
volumes:
  mongodb-ecomm:
