version: "3.3"
services:
  product:
    container_name: ecomm-product
    build: ./product
    ports:
      - 3001:3001
    volumes:
      - ./product:/app-product
  account:
    container_name: ecomm-account
    build: ./account
    ports:
      - 3002:3002
    volumes:
      - ./account:/app-account
  mongodb:
    image: mongo:5
    restart: always
    container_name: mongo-ecomm
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    ports:
      - 27017:27017
    volumes:
      - mongodb-ecomm:/var/lib/mongodb
  mysql:
    image: mysql
    restart: always
    container_name: mysql-ecomm
    environment:
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - 3306:3306
    volumes:
      - mysqldb-ecomm:/var/lib/mysql

volumes:
  mongodb-ecomm:
  mysqldb-ecomm:
  