openapi: 3.0.1
info:
  title: Ecomm Products
  description: API para produtos de um e-comm
  version: 0.0.1
  contact:
    name: Suporte a Dev
    email: layssahillary@pagonxt.com
    url: https://github.com/LayssaHillary/ecomm
paths:
  /api/categories:
    get:
      summary: Recupera todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categorias'
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categorias:
      type: array
      items:
        $ref: '#/components/schemas/Categoria'

 