openapi: 3.0.1
info:
  title: Ecomm Products
  description: API para produtos de um e-comm
  version: 0.0.1
  contact:
    name: Suporte a Dev
    email: layssahillary@pagonxt.com
    url: https://github.com/LayssaHillary/ecomm
paths:

  /api/categories:
    get:
      summary: Recupera todas as categorias
      responses:
        200:
          description: Sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categorias'
                
  /api/admin/categories:
    post:
      summary: Criar nova categoria
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                descricao:
                  type: string
      responses:
        201:
          description: Categoria criada com sucesso
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Categoria"

  /api/categories/{id}:
    parameters:
    - name: id
      in: path
      schema:
        type: integer
      required: true
    get:
      summary: Recupera uma categoria pelo ID
      responses:
        200:
          description: Categoria pelo ID recuperada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Categoria'
        404:
          description: ID da Categoria não encontrada
          content:
            application/json:
              example: "Not Found"
              
components:
  schemas:
    Categoria:
      type: object
      properties:
        id:
          type: integer
        nome:
          type: string
        status:
          type: string
    Categorias:
      type: array
      items:
        $ref: '#/components/schemas/Categoria'

 